#!/bin/sh

clock=$(date '+%I')

case "$clock" in
	"00") icon="🕛" ;;
	"01") icon="🕐" ;;
	"02") icon="🕑" ;;
	"03") icon="🕒" ;;
	"04") icon="🕓" ;;
	"05") icon="🕔" ;;
	"06") icon="🕕" ;;
	"07") icon="🕖" ;;
	"08") icon="🕗" ;;
	"09") icon="🕘" ;;
	"10") icon="🕙" ;;
	"11") icon="🕚" ;;
	"12") icon="🕛" ;;
esac

day=$(date | awk '{ print $3 }')

case $BLOCK_BUTTON in
    # Print calendar with current day as red, notify-send can't render the highlight so span between as red
    # Print appointments in google calendar, skip every other line which is empty
    #1) notify-send -t 0 "This Month" "$(cal --color=always | sed "s/..7m/<b><span color=\"red\">/;s|..27m|</span></b>|")" && notify-send -t 0 "Appointments" "$(gcalcli --nocolor agenda | awk '{ if (NR % 2 == 0) { print }}')" ;; # Appt if synced with gcalcli
    #1) notify-send -t 0 "This Month" "$(cal --color=always | sed "s/..7m/<b><span color=\"red\">/;s|..27m|</span></b>|")" ;; # Color didn't work
    1) notify-send -t 0 "This Month" "$(cal | sed "s/\<$(date +'%e')\>/<b><span color='red'>&<\/span><\/b>/")" ;;
	#2) notify-send "📅 Time/date module" "\- Left click to show upcoming appointments for the next three days via \`gcalcli agenda\` and show the month via \`cal\`" ;;
	2) notify-send "📅 Time/date module" "\- Left click to show the month via \`cal\`" ;;
	6) "$TERMINAL" -e "$EDITOR" "$0" ;;
esac

#date "+%Y %b %d (%a) $icon%I:%M%p"
date "+%Y %b %d (%a) %I:%M%p"
