#!/bin/sh

# Prints the current volume or 🔇 if muted.

case $BLOCK_BUTTON in
	1) amixer set Master toggle ;;
	2) notify-send "📢 Volume module" "\- Shows volume 🔊, 🔇 if muted.
- Left click to mute.
- Right Click to open audio mixer.
- Scroll to change." ;;
	3) pavucontrol ;;
	4) pamixer --allow-boost -i 1 ;;
	5) pamixer --allow-boost -d 1 ;;
	6) "$TERMINAL" -e "$EDITOR" "$0" ;;
esac

#vol="$(wpctl get-volume @DEFAULT_AUDIO_SINK@)"
vol=$(amixer get Master | tail -n1 | sed -r "s/.*\[(.*)%\].*/\1/")

# If muted, print 🔇 and exit.
#[ "$vol" != "${vol%\[MUTED\]}" ] && echo 🔇 && exit
if [ $(pacmd list-sinks | awk '/muted/ { print $2 }' | awk 'NR==1{print $1}') == "yes" ]
then
    vol=-1
fi

vol="${vol#Volume: }"
split() {
	# For ommiting the . without calling and external program.
	IFS=$2
	set -- $1
	printf '%s' "$@"
}
vol="$(split "$vol" ".")"
#vol="${vol##0}"

case 1 in
	$((vol >= 70)) ) icon="🔊" ;;
	$((vol >= 30)) ) icon="🔉" ;;
	$((vol >= 0)) ) icon="🔈" ;;
	* ) echo 🔇 && exit ;;
esac

echo "$icon$vol%"
