#!/bin/sh

# Prints the current volume or 🔇 if muted.

case $BLOCK_BUTTON in
	1) amixer set Master toggle ;;
	2) notify-send "📢 Volume module" "\- Shows volume 🔊, 🔇 if muted.
        - Left click to mute.
        - Right Click to toggle between headphones and speakers.
        - Middle click for info and open audio mixer.
        - Scroll to change." && 
        pavucontrol;;
	3) swtchaudio ;;
	4) amixer set "Master" 1%+ ;;
	5) amixer set "Master" 1%- ;;
	6) "$TERMINAL" -e "$EDITOR" "$0" ;;
esac

vol=$(amixer get Master | tail -n1 | sed -r "s/.*\[(.*)%\].*/\1/")

# If muted, print 🔇 and exit.
if [ $(amixer get Master | awk 'NR==6{print $6}') == "[off]" ]
then
    vol=-1
fi

vol="${vol#Volume: }"
split() {
	# For ommiting the . without calling and external program.
	IFS=$2
	set -- $1
	printf '%s' "$@"
}
vol="$(split "$vol" ".")"

hdphn="Headphone"
cardnum=$(aplay -l | grep 'HDA Creative' | awk 'NR==1{gsub(/:/,""); print $2}')
crntaudio=$(amixer -c $cardnum get 'Output Select' | awk -F: 'NR==4{gsub(/ /, ""); gsub("\047",""); print $2 }')
if [ "$crntaudio" == "$hdphn" ]
then
    preicon="🎧"
else
    preicon=""
fi

case 1 in
	$((vol >= 70)) ) icon="${preicon}🔊" ;;
	$((vol >= 30)) ) icon="${preicon}🔉" ;;
	$((vol >= 0)) ) icon="${preicon}🔈" ;;
	* ) echo 🔇 && exit ;;
esac

echo "$icon$vol%"
